@api = http://localhost:3000

POST {{api}}/register 
Content-Type: application/json

{
    "password": "password",
    "email": "test@example.com",
    "name": "super User"
}

###
GET {{api}}/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password"
}

###
DELETE {{api}}/3/delete

###
POST {{api}}/1/task/create
Content-Type: application/json

{
    "name": "¿¿¿¿",
    "description": "si yuuuu",
    "creation_date": "2024-04-28",
    "due_date": "2024-05-30",
    "category": "turtle",
    "importance": "High",
    "completed": false
}

###
GET {{api}}/1/tasks

###
DELETE {{api}}/1/task/4/delete

###
PUT {{api}}/1/task/1/update
Content-Type: application/json

{
    "name": "update test",
    "due_date": "2024-05-01"
}

###
GET {{api}}/1/tasks/turtle